# Generated by Django 5.1.7 on 2025-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_variations'),
        ('orders', '0002_remove_orderproduct_variations'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='clothings', to='store.color'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='footwears', to='store.color'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='clothings', to='store.size'),
        ),
        migrations.AddField(
            model_name='footwear',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='footwears', to='store.size'),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
