# Generated by Django 5.1.7 on 2025-04-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_size_clothing_colors_footwear_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='footwear',
            name='sizes',
        ),
        migrations.AddField(
            model_name='footwear',
            name='footsizes',
            field=models.ManyToManyField(blank=True, related_name='footwears', to='store.footsize'),
        ),
    ]
