# Generated by Django 5.1.7 on 2025-04-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_footsize_remove_footwear_sizes_footwear_footsizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footsize',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
