# Generated by Django 5.1.7 on 2025-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_footsize_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisions',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='provisions', to='store.color'),
        ),
    ]
