# Generated by Django 5.1.7 on 2025-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_color_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='footsizes',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
