# Generated by Django 5.1.7 on 2025-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_footsizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='footsizes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
