# Generated by Django 5.1.7 on 2025-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
